name: Bonsoir
repository: https://github.com/Skyost/Bonsoir

packages:
  - packages/*
  - packages/bonsoir/example

command:
  version:
    linkToCommits: true
    branch: master
    workspaceChangelog: false
    hooks:
      pre: dart format "packages/bonsoir/lib" && cd "packages/bonsoir_platform_interface" && dart run "bonsoir_platform_interface:generate" && cd "../../" && melos analyze
    message: |
      chore(release): Publish packages.

      {new_package_versions}
    changelogs:
      - path: packages/bonsoir/CHANGELOG.md
        description: |
          All notable changes to Bonsoir packages will be documented in this file.
        packageFilters:
          scope: bonsoir*

scripts:
  analyze:
    exec: dart analyze .
