name: Bonsoir
repository: https://github.com/Skyost/Bonsoir

packages:
  - packages/*
  - packages/bonsoir/example

command:
  version:
    linkToCommits: true
    branch: master
    workspaceChangelog: false
    updateGitTagRefs: false
    hooks:
      pre: |
        cd packages/bonsoir_platform_interface
        dart run bonsoir_platform_interface:generate
        cd ../../
        melos analyze
    message: |
      chore(release): Publish packages.

      {new_package_versions}

scripts:
  analyze:
    exec: dart analyze .
