name: bonsoir_tests
description: Demonstrates how to use the bonsoir plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  device_info: ^2.0.0
  provider: ^5.0.0
  flutter:
    sdk: flutter
  bonsoir:
    path: ../

dev_dependencies:
  pedantic: '>=1.8.0 <2.0.0'
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  
flutter:
  uses-material-design: true
