name: bonsoir
description: A Zeroconf library that allows you to discover network services and to broadcast your own. Based on Apple Bonjour and Android NSD.
version: 1.0.0 # Remember to also change the version in "ios/bonsoir.podspec", "macos/bonsoir.podspec", and "android/build.gradle".
homepage: https://github.com/Skyost/Bonsoir

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface

dev_dependencies:
  pedantic: '>=1.8.0 <2.0.0'
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.bonsoir
        pluginClass: BonsoirPlugin
      ios:
        pluginClass: BonsoirPlugin
      macos:	
        pluginClass: BonsoirPlugin
