name: bonsoir_darwin
description: Darwin (iOS & macOS) implementation of the Bonsoir plugin.
repository: https://github.com/Skyost/Bonsoir/tree/master/bonsoir_darwin
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      ios:
        pluginClass: BonsoirPlugin
      macos:
        pluginClass: BonsoirPlugin

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ^2.0.0
