name: bonsoir_platform_interface
description: Common platform interface for the Bonsoir plugin.
homepage: https://github.com/Skyost/Bonsoir
version: 1.0.0+1
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0
  bonsoir:
    path: ../bonsoir
dev_dependencies:
  pedantic: '>=1.8.0 <2.0.0'
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
