name: bonsoir_platform_interface
description: Common platform interface for the Bonsoir plugin.
homepage: https://github.com/Skyost/Bonsoir

version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  pedantic: '>=1.8.0 <2.0.0'
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"
