name: bonsoir_platform_interface
description: Common platform interface for the Bonsoir plugin.
homepage: https://github.com/Skyost/Bonsoir
version: 3.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ">=4.0.0 <4.1.0"
  meta: ">=1.9.0 <2.0.0"
  plugin_platform_interface: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^3.0.1
