name: bonsoir_example
description: Demonstrates how to use the bonsoir plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir:
    path:
      ../
  flutter_riverpod: ^2.4.6
  device_info_plus: ^9.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^3.0.1

dependency_overrides:
  bonsoir_platform_interface:
    path: ../../bonsoir_platform_interface/
  bonsoir_android:
    path: ../../bonsoir_android/
  bonsoir_darwin:
    path: ../../bonsoir_darwin/
  bonsoir_windows:
    path: ../../bonsoir_windows/
  bonsoir_linux:
    path: ../../bonsoir_linux/

flutter:
  uses-material-design: true
